services:
  cloudflared_dummy:
    image: cloudflare/cloudflared:latest
    container_name: form14_cloudflared_dummy
    user: "0:0"
    command:
      - tunnel
      - --no-autoupdate
      - --loglevel
      - info
      - run
      - --token-file
      - /run/secrets/cloudflare_dummy_tunnel_token
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./.cloudflared/dummy-tunnel.token:/run/secrets/cloudflare_dummy_tunnel_token:ro
    restart: unless-stopped
